services:
  - type: web
    name: acquasystems
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    plan: free